### ISSUE TITLE
Set up Mongo DB Integration

### ISSUE THREAD

**Issue by cow-co** [cow-co/RIME#2]
Using Mongoose, connect to the Mongo DB instance.

**Comment by AhmedElbohoty** [comment]
@cow-co .
Hello my friend. 

If there is place i want to work with you :)

**Comment by cow-co** [comment]
Sorry, I kinda want this to be a solo project. Honestly, it would probably not be very fun for you to work on either, since I'm doing this in my spare time, so I will be quite slow to work at it and so on.

Feel free to fork the repo and see what you can do with it though.

Sorry again, just I don't want the responsibility associated with working with other people on this. Hope you find something that works for you though :)

**Comment by AhmedElbohoty** [comment]
No problem at all my friend. Thanks :)
